[package]
name = "securepwd"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
dotenv = { version = "0.15", default-features = false }

[dependencies]
wasm-bindgen = "0.2"
sha2 = "0.10"
hex = "0.4"
lazy_static = "1.4"
